apiVersion: v1
kind: ConfigMap
metadata:
  name: welcome-app-configmap
data:
  WELCOME_MESSAGE: "Selamat datang boss!"

---
apiVersion: v1
kind: Secret
metadata:
  name: welcome-app-secret
type: Opaque