name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag version"
        required: true
      branch:
        description: "Branch to build and deploy"
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/testing-welcome:latest -t ${{ secrets.DOCKER_USERNAME }}/testing-welcome:${{ github.event.inputs.tag_version }} .

      - name: Push docker image to docker hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/testing-welcome:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/testing-welcome:${{ github.event.inputs.tag_version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP } << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/testing-welcome:${{ github.event.inputs.tag_version }}
          docker stop welcome-app || true
          docker rm welcome-app || true
          docker run -d --name welcome-app -p 8000:5000 --restart unless-stopped testing/welcome:${{ github.event.inputs.tag_version }}